use anyhow::{Context, Result};
use std::path::{Path, PathBuf};

const RUN_SH: &str = r#"#!/usr/bin/env bash
# Generated by fkst-framework init-package-repo.
set -euo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

python3 "$repo/scripts/check_repo.py"

framework_bin="${FKST_FRAMEWORK_BIN:-}"
if [[ -z "$framework_bin" ]]; then
  substrate_ref="$(< "$repo/.fkst-substrate-ref")"
  substrate_ref="${substrate_ref%%$'\n'*}"
  substrate_ref="${substrate_ref%$'\r'}"
  if [[ -z "$substrate_ref" ]]; then
    echo "scripts/run.sh: .fkst-substrate-ref must not be empty" >&2
    exit 1
  fi

  substrate_repo="${FKST_SUBSTRATE_REPO:-https://github.com/ChronoAIProject/fkst-substrate.git}"
  substrate_src="${FKST_SUBSTRATE_SRC:-$repo/.fkst/substrate-src}"
  if [[ ! -d "$substrate_src/.git" ]]; then
    if [[ -e "$substrate_src" ]]; then
      echo "scripts/run.sh: FKST_SUBSTRATE_SRC exists but is not a git checkout: $substrate_src" >&2
      exit 1
    fi
    mkdir -p "$(dirname "$substrate_src")"
    git clone "$substrate_repo" "$substrate_src"
  fi
  git -C "$substrate_src" fetch --tags origin
  git -C "$substrate_src" checkout --detach "$substrate_ref"
  cargo build --manifest-path "$substrate_src/Cargo.toml" -p fkst-framework --release
  framework_bin="$substrate_src/target/release/fkst-framework"
fi

export FKST_RUNTIME_ROOT="${FKST_RUNTIME_ROOT:-$repo/.fkst/runtime}"

"$framework_bin" --self-test
"$framework_bin" conformance --project-root "$repo" --package-root "$repo"
"$framework_bin" test --project-root "$repo" --package-root "$repo"
"#;

const CHECK_REPO_PY: &str = r#"#!/usr/bin/env python3
# Generated by fkst-framework init-package-repo.
from pathlib import Path
import os
import stat
import sys


REQUIRED_FILES = [
    "scripts/run.sh",
    "scripts/check_repo.py",
    ".github/workflows/ci.yml",
    "env.example",
    ".fkst-substrate-ref",
]


def fail(message: str) -> None:
    print(f"check_repo.py: {message}", file=sys.stderr)
    sys.exit(1)


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    if not (root / ".git").exists():
        fail("repository root must contain .git")

    for rel in REQUIRED_FILES:
        if not (root / rel).is_file():
            fail(f"missing required scaffold file: {rel}")

    ref = (root / ".fkst-substrate-ref").read_text(encoding="utf-8").strip()
    if not ref:
        fail(".fkst-substrate-ref must not be empty")

    run_sh = root / "scripts/run.sh"
    mode = stat.S_IMODE(os.stat(run_sh).st_mode)
    if mode & stat.S_IXUSR == 0:
        fail("scripts/run.sh must be executable")


if __name__ == "__main__":
    main()
"#;

const CI_YML: &str = r#"name: ci

on:
  push:
    branches: [dev, integration, "integration-*"]
  pull_request:
    branches: [dev, integration, "integration-*"]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run package gates
        run: ./scripts/run.sh
"#;

const ENV_EXAMPLE: &str = r#"# Copy this file to fkst.env and set host facts for local runs.
FKST_FRAMEWORK_BIN=fkst-framework
FKST_RUNTIME_ROOT=.fkst/runtime
FKST_CANDIDATE_PREFIX=candidate
FKST_CANDIDATE_FROM_SEP=__from__
"#;

const README_MD: &str = r#"# fkst package repo

This repository is an fkst package or host root. Refresh the scaffold with:

```sh
fkst-framework init-package-repo
```

Run local validation with:

```sh
scripts/run.sh
```

Copy `env.example` to `fkst.env` when local departments need host facts.
"#;

const GITIGNORE_ENTRIES: &[&str] = &[".fkst/", "fkst.env", "target/", "__pycache__/", "*.pyc"];

#[derive(Clone, Debug)]
pub(crate) struct InitPackageRepoOptions {
    pub(crate) substrate_ref: String,
    pub(crate) force: bool,
}

#[derive(Clone, Debug, PartialEq, Eq)]
enum PlannedAction {
    Create,
    Unchanged,
    Refuse,
    AppendEntries(Vec<&'static str>),
}

#[derive(Clone, Debug)]
struct TemplateFile {
    rel: &'static str,
    content: String,
    executable: bool,
}

pub(crate) fn run(options: InitPackageRepoOptions) -> Result<i32> {
    let repo_root = find_repo_root(&std::env::current_dir().context("read current directory")?)
        .context("init-package-repo must run inside a git repository")?;
    let files = template_files(&options.substrate_ref);
    let mut plans = Vec::new();
    for file in &files {
        plans.push((
            file.rel,
            plan_file(&repo_root.join(file.rel), &file.content)?,
        ));
    }
    let gitignore_plan = plan_gitignore(&repo_root)?;

    print_report_header(&repo_root, &options.substrate_ref, options.force);
    for (rel, action) in &plans {
        print_action(rel, action, options.force);
    }
    print_action(".gitignore", &gitignore_plan, options.force);

    let refused: Vec<&str> = plans
        .iter()
        .filter_map(|(rel, action)| (*action == PlannedAction::Refuse).then_some(*rel))
        .collect();
    if !refused.is_empty() && !options.force {
        anyhow::bail!(
            "init-package-repo refused local edits in {}; rerun with --force to overwrite or compare against a fresh scaffold in a scratch repository",
            refused.join(", ")
        );
    }

    for file in &files {
        apply_file(&repo_root.join(file.rel), &file.content, file.executable)?;
    }
    apply_gitignore(&repo_root, gitignore_plan)?;
    Ok(0)
}

fn template_files(substrate_ref: &str) -> Vec<TemplateFile> {
    vec![
        TemplateFile {
            rel: "scripts/run.sh",
            content: RUN_SH.to_string(),
            executable: true,
        },
        TemplateFile {
            rel: "scripts/check_repo.py",
            content: CHECK_REPO_PY.to_string(),
            executable: false,
        },
        TemplateFile {
            rel: ".github/workflows/ci.yml",
            content: CI_YML.to_string(),
            executable: false,
        },
        TemplateFile {
            rel: "env.example",
            content: ENV_EXAMPLE.to_string(),
            executable: false,
        },
        TemplateFile {
            rel: ".fkst-substrate-ref",
            content: format!("{substrate_ref}\n"),
            executable: false,
        },
        TemplateFile {
            rel: "README.md",
            content: README_MD.to_string(),
            executable: false,
        },
    ]
}

fn find_repo_root(start: &Path) -> Option<PathBuf> {
    for candidate in start.ancestors() {
        if candidate.join(".git").exists() {
            return Some(candidate.to_path_buf());
        }
    }
    None
}

fn plan_file(path: &Path, expected: &str) -> Result<PlannedAction> {
    if !path.exists() {
        return Ok(PlannedAction::Create);
    }
    let actual =
        std::fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
    if actual == expected {
        Ok(PlannedAction::Unchanged)
    } else {
        Ok(PlannedAction::Refuse)
    }
}

fn plan_gitignore(repo_root: &Path) -> Result<PlannedAction> {
    let path = repo_root.join(".gitignore");
    if !path.exists() {
        return Ok(PlannedAction::Create);
    }
    let actual =
        std::fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
    let existing = actual
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .collect::<std::collections::BTreeSet<_>>();
    let missing = GITIGNORE_ENTRIES
        .iter()
        .copied()
        .filter(|entry| !existing.contains(entry))
        .collect::<Vec<_>>();
    if missing.is_empty() {
        Ok(PlannedAction::Unchanged)
    } else {
        Ok(PlannedAction::AppendEntries(missing))
    }
}

fn apply_file(path: &Path, content: &str, executable: bool) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
    }
    if path.exists() {
        let actual =
            std::fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
        if actual == content {
            set_executable(path, executable)?;
            return Ok(());
        }
    }
    std::fs::write(path, content).with_context(|| format!("write {}", path.display()))?;
    set_executable(path, executable)
}

fn apply_gitignore(repo_root: &Path, action: PlannedAction) -> Result<()> {
    let path = repo_root.join(".gitignore");
    match action {
        PlannedAction::Create => {
            let content = GITIGNORE_ENTRIES.join("\n") + "\n";
            std::fs::write(&path, content).with_context(|| format!("write {}", path.display()))
        }
        PlannedAction::AppendEntries(entries) => {
            let mut content = std::fs::read_to_string(&path)
                .with_context(|| format!("read {}", path.display()))?;
            if !content.is_empty() && !content.ends_with('\n') {
                content.push('\n');
            }
            for entry in entries {
                content.push_str(entry);
                content.push('\n');
            }
            std::fs::write(&path, content).with_context(|| format!("write {}", path.display()))
        }
        PlannedAction::Unchanged => Ok(()),
        PlannedAction::Refuse => unreachable!("invalid gitignore plan"),
    }
}

fn set_executable(path: &Path, executable: bool) -> Result<()> {
    if !executable {
        return Ok(());
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut permissions = std::fs::metadata(path)
            .with_context(|| format!("stat {}", path.display()))?
            .permissions();
        let mode = permissions.mode();
        permissions.set_mode(mode | 0o755);
        std::fs::set_permissions(path, permissions)
            .with_context(|| format!("chmod +x {}", path.display()))?;
    }
    Ok(())
}

fn print_report_header(repo_root: &Path, substrate_ref: &str, force: bool) {
    println!("init-package-repo repo={}", repo_root.display());
    println!("init-package-repo substrate_ref={substrate_ref}");
    println!("init-package-repo force={force}");
}

fn print_action(rel: &str, action: &PlannedAction, force: bool) {
    match action {
        PlannedAction::Create => println!("CREATE {rel}"),
        PlannedAction::Unchanged => println!("UNCHANGED {rel}"),
        PlannedAction::Refuse if force => println!("OVERWRITE {rel} differs"),
        PlannedAction::Refuse => {
            println!("REFUSE {rel} differs; hint=compare with a fresh init-package-repo scaffold")
        }
        PlannedAction::AppendEntries(entries) => {
            println!("APPEND {rel} entries={}", entries.join(","));
        }
    }
}
