[package]
name = "fkst-framework"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "fkst-framework"
path = "src/main.rs"

[dependencies]
fkst-common = { path = "../fkst-common" }
mlua = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = "0.8"
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
nix = { workspace = true }
base64 = { workspace = true }
ulid = { workspace = true }
tokio = { workspace = true }
notify = { workspace = true }
redb = "2.6.3"
tempfile = "3"

[dev-dependencies]
filetime = "0.2"
