[package]
name = "fkst-update"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "fkst-update"
path = "src/main.rs"

[dependencies]
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
