#!/usr/bin/env bash
# Operator-convenience installer for fkst-substrate. NOT engine surface.
#
# It builds the workspace in release mode, installs both engine binaries into a
# bin dir, ensures an operator package root exists, and generates an operator
# launcher that sets FKST_PACKAGE_ROOT / FKST_RUNTIME_ROOT in the environment.
#
# The engine binaries carry NO default package root: fkst-framework fails closed
# without FKST_PACKAGE_ROOT or --package-root. The "~/fkst-packages" default is
# operator config that lives ONLY in the generated launcher below, never inside
# the binary, SPEC, or conformance. Override any path via the FKST_* env vars.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Operator-overridable paths. Defaults are conveniences, not engine contract.
FKST_HOME="${FKST_HOME:-$HOME/fkst}"
FKST_PACKAGE_ROOT="${FKST_PACKAGE_ROOT:-$HOME/fkst-packages}"
FKST_RUNTIME_ROOT="${FKST_RUNTIME_ROOT:-$FKST_HOME/runtime}"

bin_dir="$FKST_HOME/bin"
launcher="$bin_dir/fkst-run"

if ! command -v cargo >/dev/null 2>&1; then
  echo "fkst install: cargo not found; install Rust toolchain first" >&2
  exit 1
fi

echo "fkst install: repo=$repo_root home=$FKST_HOME package_root=$FKST_PACKAGE_ROOT"

# Build the workspace (release). Same crates the verify gate builds.
( cd "$repo_root" && cargo build --release --workspace )

# Install both engine binaries plus the fkst-update deploy client.
mkdir -p "$bin_dir"
install -m 0755 "$repo_root/target/release/fkst-supervisor" "$bin_dir/fkst-supervisor"
install -m 0755 "$repo_root/target/release/fkst-framework" "$bin_dir/fkst-framework"
install -m 0755 "$repo_root/target/release/fkst-update" "$bin_dir/fkst-update"

# Ensure the operator package root and runtime scratch exist.
mkdir -p "$FKST_PACKAGE_ROOT" "$FKST_RUNTIME_ROOT"

# Generate the operator launcher. The default package root is expressed HERE
# (operator config), and stays overridable at run time via the same env vars.
cat > "$launcher" <<EOF
#!/usr/bin/env bash
# Generated by scripts/install.sh. Operator config, not engine surface.
# Edit FKST_* below (or export them before calling) to retarget.
set -euo pipefail
export FKST_PACKAGE_ROOT="\${FKST_PACKAGE_ROOT:-$FKST_PACKAGE_ROOT}"
export FKST_RUNTIME_ROOT="\${FKST_RUNTIME_ROOT:-$FKST_RUNTIME_ROOT}"
export FKST_FRAMEWORK_BIN="$bin_dir/fkst-framework"
mkdir -p "\$FKST_PACKAGE_ROOT" "\$FKST_RUNTIME_ROOT"
# fkst-supervisor uses its cwd as the host/project root; PKG == HOST here.
cd "\$FKST_PACKAGE_ROOT"
exec "$bin_dir/fkst-supervisor" "\$@"
EOF
chmod 0755 "$launcher"

# Validate the generated launcher before declaring success.
bash -n "$launcher"

echo "fkst install: done"
echo "  binaries:     $bin_dir/fkst-supervisor, $bin_dir/fkst-framework, $bin_dir/fkst-update"
echo "  launcher:     $launcher"
echo "  package root: $FKST_PACKAGE_ROOT"
echo "  start:        $launcher"
echo "Add $bin_dir to PATH to call 'fkst-run' directly."
